#!/bin/sh
 
#
# chkconfig: 35 99 99
# description: Node.js /home/nodejs/sample/app.js
#
#sudo -u ubuntu /usr/bin/npm start /home/ubuntu/YapZap-express/
USER="ubuntu"
 
DAEMON="/usr/bin/node"
ROOT_DIR="/home/ubuntu/YapZap-express/"
APP_LOC="$ROOT_DIR/app.js" 
LOG_FILE="$ROOT_DIR/app.js.log"
LOCK_FILE="/var/lock/subsys/node-server"

 
do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                printenv
                cd $ROOT_DIR
		sudo -u $USER NODE_ENV=production $DAEMON $APP_LOC  >> $LOG_FILE & 
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`netstat -lpn | grep 'node' | awk '{print $7}' | awk -F '/' '{print $1}'`
        echo "killing " & $pid        
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}
 
case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL
